### ISSUE TITLE
Read Ists issue

### ISSUE THREAD

**Issue by kscccc** [epsilonrt/modbus-arduino#1]
It should return 0D 02 02 FF FF but coil 8 looks wrong?
![image](https://user-images.githubusercontent.com/10938462/230755667-8d2c022e-b2f8-40af-9f1a-04fb5a3df361.png)

**Comment by epsilonrt** [comment]
what is the platform ? and the version of modbus-arduino and modbus-serial ?

**Comment by epsilonrt** [comment]
```
#include <Arduino.h>
#include <ModbusSerial.h>

ModbusSerial mb (Serial, 10);

const uint8_t NbOfIsts = 24;
const uint16_t FirstIsts = 197;
const uint32_t IstsValues = 0xB5DBAC;

void setup() {

  Serial.begin (38400);
  mb.config (38400);

  for (uint8_t i = 0; i < NbOfIsts; i++) {

    mb.addIsts (FirstIsts -1 + i, (IstsValues & (1 << i)) != 0);
  }
}

void loop() {

  mb.task();
}
```

**Reading test with mbpoll :**

```
C:\Users\pasca>mbpoll -a10 -b38400 -t1 -r197 -c24 -1 -v com6
mbpoll 0.1-19 - FieldTalk(tm) Modbus(R) Master Simulator
Copyright (c) 2015 Pascal JEAN aka epsilonRT
All rights reserved.
This software is governed by the CeCILL license <http://www.cecill.info>

Opening com6 at 38400 bauds (E, 8, 1)
Protocol configuration: Modbus RTU
Slave configuration...: address = [10]
                        start reference = 197, count = 24
Communication.........: com6, 38400-8E1
                        t/o 1.00 s, poll rate 1000 ms
Data type.............: discrete input

-- Polling slave 10...
[0A][02][00][C4][00][18][38][86]
Waiting for a confirmation...
<0A><02><03><2C><DB><B5><23><BB>
[197]:  0
[198]:  0
[199]:  1
[200]:  1
[201]:  0
[202]:  1
[203]:  0
[204]:  0
[205]:  1
[206]:  1
[207]:  0
[208]:  1
[209]:  1
[210]:  0
[211]:  1
[212]:  1
[213]:  1
[214]:  0
[215]:  1
[216]:  0
[217]:  1
[218]:  1
[219]:  0
[220]:  1
```

The bug is confirmed, investigations in progress.

**Comment by kscccc** [comment]
> what is the platform ? and the version of modbus-arduino and modbus-serial ?

Arduino 1.8.15
Arduino AVR Boards 1.8.6
Arduino Mega2560
modbus-arduino 1.1.1
modbus-serial 2.0.4

Attach my test code

**Comment by epsilonrt** [comment]
THANKS.
Could you update modbus-arduino to version 1.1.1 and verify that your problem is gone ?
https://github.com/epsilonrt/modbus-arduino/archive/refs/tags/v1.1.1.zip

**Comment by kscccc** [comment]
> THANKS. Could you update modbus-arduino to version 1.1.1 and verify that your problem is gone ? https://github.com/epsilonrt/modbus-arduino/archive/refs/tags/v1.1.1.zip

Tested version 1.1.1 and verify. It work normal now. Thanks
