### ISSUE TITLE
Example program would help new developers to find a starting point

### ISSUE THREAD

**Issue by ashrafulkhn** [epsilonrt/modbus-arduino#6]
Hi @epsilonrt ,
I appreciate your work with the modbus-arduino library. Your additions will definitely be a great contribution to the community.
In addition to that, I would like to ask you to provide some examples using functions 1 3, 6, and 10. For starters, that will be a good starting point.

**Comment by epsilonrt** [comment]
Hi,
modbus-arduino is the base class, if you want examples, you can consult them for example in the modbus-serial library (as indicated in the README): https://github.com/epsilonrt/modbus-serial/tree/master/examples
